### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by DarkWoodens** [DotOS/android_packages_apps_Extra_dots#1]
![image](https://user-images.githubusercontent.com/19311643/28087465-3322d950-668b-11e7-9b40-c403ae6baf80.png)

**Comment by mohancm100** [comment]
Source is derp, right now!!
Will fix it soon

**Comment by dg28gadhavi** [comment]
Lol Sorry to say but our ROM is still W.I.P i hope you can understand ditch that dotextras from manifest and remove it the build should go fine but remember it has nothing it's W.I.P @IacobIonut
